' Tính năng quản lý chi cho cho CTV sẽ có hai hình thức ghi nhận thủ công từ chủ shop và momo:
' + Quản lý chi qua momo đã hoàn tất
' + Quản lý chi qua ghi nhận CTV sẽ ghi nhận đã chi yêu cầu cần nhập nội dung chi và hình ảnh đính kèm - hình unc, hình chụp màn hình chi tiền, chứng từ khi thực hiện ghi chú là đã thanh toán

' Hình thức chi cho CTV có thể setting ở chủ shop với hình thức:
' + Bật tắt tính/năng ghi nhận chi cho CTV
' + Chọn chi tự động qua momo (như luồng đã làm), ghi nhận thủ công hoặc cả hai

@startuml

map Customer {
  momoWalletStatus => Trạng thái ví Momo
}

enum MomoWalletStatus {
  invalid
  wallet_invalid
  wallet_not_found
  valid
  delivery_not_found
}

Customer --* MomoWalletStatus

map CustomerCommissionDisburse {
  customerId ==> ID khách hàng
  type => Loại chi
  amount => Số tiền chi
  images => Hình ảnh
  note => Ghi chú
  status => Trạng thái
  momo => Thông tin momo
}

Customer --{ CustomerCommissionDisburse 

enum DisburseType {
  momo
  manual
}

CustomerCommissionDisburse --> DisburseType

enum DisburseStatus {
  pending
  success
  failed
}

CustomerCommissionDisburse --> DisburseStatus
@enduml
